#!/usr/bin/env python3
"""Render MCV-Semantic-Factorization-v0 results."""
import argparse,json
from pathlib import Path

def main():
 p=argparse.ArgumentParser();p.add_argument('input',type=Path);p.add_argument('--output',type=Path,required=True);a=p.parse_args();d=json.loads(a.input.read_text());r=d['reconstruction'];agg=d['aggregate_exhaustive'];rows=d['queries'];total=r['bitwise_exact']+r['tolerance_exact_nonbitwise']+r['divergent']
 out=["# MCV-Semantic-Factorization-v0","","## Verdict","",
 "The conservative source-derived dependency graph does **not** split any nonempty Census query into multiple factors. Every query contains all pair candidates over its predicate columns; overlap edges therefore form the connected line graph of a complete column graph. This is **Outcome E**: exact numerical composition exists, but fixed-universe semantic factorization offers no exponential response-table reduction on Census.","",
 "## Source-derived dependency graph","",
 "A node is one relevant MCV candidate. Two nodes are connected if their complete compatible-clause scopes may overlap in any reachable state. Complete scope includes attributes and statistics expressions; plain `stxkeys` intersection is not used. Connected components are the conservative factors.","",
 "PostgreSQL computes each winner's `stat_sel` using `mcv_clauselist_selectivity()` and `mcv_combine_selectivities()`, then updates the AND-path accumulator with `sel *= stat_sel`. In the frozen replay IR, each candidate stores the normalized correction `stat_sel/simple_sel`; hence a factor can expose one normalized multiplier and the query estimate is reconstructed as `baseline_rows * product(factor_multiplier)`.","",
 "Mathematically the normalized factors compose multiplicatively, so composition is commutative and associative. IEEE-754 regrouping is not universally associative; native bitwise reproduction requires retaining and merging the OID-ordered contribution streams.","",
 "## Factor interfaces","",
 "| interface | contents | result |", "|---|---|---|",
 "| F1 | one normalized scalar correction multiplier | smallest tolerance-exact interface |",
 "| F2 | F1 plus local simple selectivity | redundant after normalization |",
 "| F3 | F1 plus consumed-clause identity | useful for control auditing; does not repair FP regrouping |",
 "| F4 | OID-ordered local winner/contribution stream | bitwise exact, but violates the anti-triviality rule by retaining local execution history |","",
 f"F1 reconstructed all {total:,} evaluated designs within relative tolerance `1e-12`: {r['bitwise_exact']:,} ({r['bitwise_exact']/total:.2%}) were bitwise exact and {r['tolerance_exact_nonbitwise']:,} ({r['tolerance_exact_nonbitwise']/total:.2%}) differed only by floating-point regrouping. Maximum exhaustive-query relative error was {agg['max_relative_error']['max']:.3e}. F4 was bitwise exact for all {r['F4_bitwise_exact']:,} designs, but is not accepted as a compact interface.","",
 "## Validation coverage","",
 f"All {d['scope']['exhaustive_queries']} queries with at most {d['scope']['exhaustive_threshold']} candidates were exhaustively evaluated ({agg['subsets']:,} subsets). The other {d['scope']['sampled_queries']} queries used 4,096 deterministic subsets each. Total direct/factorized comparisons: {d['scope']['subsets_checked']:,}. Divergences: {r['divergent']}.","",
 "Across the exhaustive domain:","",
 f"- exactly reconstructed queries: {agg['exactly_factorized']}/{agg['queries']};",
 f"- queries with counterexamples: {agg['with_counterexamples']};",
 f"- single-factor queries: {agg['single_factor_queries']};",
 f"- multi-factor queries: {agg['multi_factor_queries']};",
 f"- median/mean/p95/max factor count: {agg['factor_count']['median']:.3f} / {agg['factor_count']['mean']:.3f} / {agg['factor_count']['p95']:.3f} / {agg['factor_count']['max']};",
 f"- median/mean/p95/max largest-factor size: {agg['max_factor_size']['median']:.3f} / {agg['max_factor_size']['mean']:.3f} / {agg['max_factor_size']['p95']:.3f} / {agg['max_factor_size']['max']};",
 f"- median dependency density: {agg['dependency_density']['median']:.3f};",
 "- structural log2 enumeration reduction: 0 for every query.","",
 "The one zero-candidate query has zero factors. Every other Census query has exactly one factor, including sampled queries up to 91 candidates.","",
 "## Nontrivial two-factor and background-invariance fixture","",
 "To test actual composition rather than only the Census single-factor identity, a restricted frozen query.4 fixture uses candidate 230 on `(dincome2,isex)` and candidate 448 on `(dincome7,drearning)`. Their scopes are disjoint, producing two singleton factors. All four designs reconstructed bitwise exactly. Four cross-factor background-invariance checks found zero failures.","",
 "This fixture shows that the source-derived composition works when a nontrivial factor split exists. It does not change the negative Census structural result.","",
 "## Expression safety","",
 "The synthetic expression fixture places `(a, lower(t))` and `(b, lower(t))` in the same factor. Although ordinary attribute `stxkeys` are disjoint, the shared expression clause creates a semantic dependency edge. This prevents the unsafe split identified in MCV-Commutativity-v0.","",
 "## Structural enumeration complexity","",
 "For each nonempty Census query, the sole factor has size `m_q`. Therefore:","",
 "```text","full log2 configurations       = m_q","factorized log2 enumeration   = log2(2^m_q) = m_q","structural log2 reduction     = 0","```","",
 "No runtime or optimizer speedup is inferred. The hypothetical factor-table cost is exactly the unfactorized response-table cost.","",
 "## Cross-factor invariance and counterexamples","",
 f"Census cross-factor invariance is vacuous because it has no multi-factor queries. The nontrivial fixture performed {d['background_invariance']['tests']} checks with {d['background_invariance']['failures']} failures. No hidden-control, incomplete-interface, simple-selectivity, or tolerance-level numerical counterexample was found. Floating-point regrouping produced non-bitwise F1 results, which is recorded as a numerical-order effect rather than hidden semantic coupling.","",
 "## Why this does not contradict CE-Semantic-State-v0","",
 "State compression asked whether distinct complete design histories could be merged into a restart-safe execution state. Factorization retains every design bit and asks whether response tables can be evaluated componentwise. These are different properties. In this workload the latter route is blocked earlier: the conservative candidate dependency graph is connected, so there is no Cartesian factor structure to exploit.","",
 "## Runtime and limitations","",
 f"Runtime: {d['runtime_seconds']:.2f} seconds.","",
 "- Main evidence is frozen Census pair-MCV, fixed precedence, and single-attribute AND predicates.",
 "- Large-query reconstruction is sampled, although graph connectivity is computed exactly for every query.",
 "- F1 is tolerance-exact, not universally bitwise exact.",
 "- F4 is a validation control, not an acceptable compact interface.",
 "- The restricted two-factor fixture proves composition behavior but not structural prevalence.",
 "- CE factorization does not make q-error additive.","",
 "## Required final answers","",
 "1. **Does the dependency relation produce nontrivial factors?** No. Every nonempty Census candidate graph is one connected component.",
 "2. **Are factor responses independent of other factors?** In the nontrivial restricted fixture, yes; Census itself has no cross-factor backgrounds to test.",
 "3. **Smallest tested interface?** One normalized scalar correction multiplier (F1) for tolerance-exact reconstruction. No compact universally bitwise-exact interface was established; F4 is bitwise exact but retains local history.",
 "4. **Can every exhaustively tested estimate be reconstructed?** Yes within `1e-12` for all 2,395,773 exhaustive designs, with zero divergences.",
 "5. **Counterexamples?** No tolerance-level semantic counterexample. Floating regrouping caused non-bitwise F1 results. No Census structural split exists.",
 "6. **Factor sizes?** The largest factor equals the complete candidate set for every nonempty query; observed maximum is 91.",
 "7. **Enumeration avoided?** None on Census: structural reduction is exactly 0 bits and ratio 1.",
 "8. **Next direction?** The evidence does not justify factorized exact/DP representation as the primary route. Semantic components may still help incremental evaluation on workloads or restricted candidate universes that actually split, but Census requires returning to semantics-guided incremental search rather than factor-table DP.","",
 "## Per-query headline table","",
 "| query | candidates | dependency edges | factors | max factor size | full log2 configs | factorized log2 enumeration | exact reconstruction? | max relative error | subsets checked | bitwise exact | tolerance exact | divergent |",
 "|---|---:|---:|---:|---:|---:|---:|:---:|---:|---:|---:|---:|---:|"]
 for x in rows:
  out.append(f"| {x['query']} | {x['candidates']} | {x['dependency_edges']} | {x['factors']} | {x['max_factor_size']} | {x['full_log2_configs']:.3f} | {x['factorized_log2_enumeration']:.3f} | {'yes' if x['exact_reconstruction'] else 'no'} | {x['max_relative_error']:.3e} | {x['subsets_checked']} | {x['bitwise_exact']} | {x['tolerance_exact']} | {x['divergent']} |")
 a.output.write_text('\n'.join(out)+'\n')
if __name__=='__main__':main()
